name: dln
description: "This package allows you to interact with the deSwap Liquidity Network (DLN)."
repository: https://github.com/naxar-wallet/dln
issue_tracker: https://github.com/naxar-wallet/dln/issues/new/choose
version: 0.0.4

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
